"""empty message

Revision ID: 27bf711ead0a
Revises: None
Create Date: 2015-05-11 00:28:48.391147

"""

# revision identifiers, used by Alembic.
revision = '27bf711ead0a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
