"""empty message

Revision ID: 54919612caa
Revises: 27bf711ead0a
Create Date: 2015-05-11 00:32:27.800008

"""

# revision identifiers, used by Alembic.
revision = '54919612caa'
down_revision = '27bf711ead0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
